---
name: Run on filtered changes
on:
  workflow_dispatch:
  push:

jobs:
  diff-test:
    name: Test repo diff
    runs-on: ubuntu-latest
    steps:
      # - name: Check out repo
      #   uses: actions/checkout@v3
      #   with:
      #     repository: cosmos/gaia
      #     path: gaia
      # - name: List files
      #   run: ls gaia
      - name: Get list of modified files
        run: |
          git clone https://github.com/cosmos/gaia.git
          cd gaia
          commit=$(git log -n 1 main --pretty=format:"%H")
          git diff-tree --no-commit-id --name-only $commit -r
      # - name: Generate diff
      #   id: git_diff
      #   uses: technote-space/get-diff-action@v6
      #   with:
      #     PATTERNS: |
      #       **/*.go
      #       go.mod
      #       go.sum
      #       **/go.mod
      #       **/go.sum
      #       **/Makefile
      #       Makefile
      #     RELATIVE: 'gaia'
      # - name: Print diff
      #   run: echo $GIT_DIFF