---
name: Run on filtered changes
on:
  workflow_dispatch:
  push:

jobs:
  diff-test:
    name: Test repo diff
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          repository: cosmos/gaia
          path: gaia
      - name: List files
        run: ls gaia