---
name: Triggering Workflow
on:
  workflow_dispatch:
  # push:

jobs:
  trigger:
    name: Trigger
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to remote workflow
        env:
            SUPER_SECRET: ${{ secrets.DANTE_PAT }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $SUPER_SECRET" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/dasanchez/hello-gh-actions/dispatches \
          -d '{"event_type":"remote_trigger","client_payload":{}}'